# Generated by Django 4.1.3 on 2022-11-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratarimagem',
            name='x',
            field=models.IntegerField(null=True, verbose_name='Largura'),
        ),
        migrations.AddField(
            model_name='tratarimagem',
            name='y',
            field=models.IntegerField(null=True, verbose_name='Altura'),
        ),
    ]
